name: ev_charging_stations
description: Able to manage All his EVs inside the app plus he has search/book a slot in advance in the charging station
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.4
  get: ^4.6.3
  get_storage: ^2.0.3
  responsive_framework: ^0.2.0
  lottie: ^1.3.0
  dio: ^4.0.6
  intl: ^0.17.0
  geolocator: ^8.2.1
  google_maps_flutter: ^2.2.5
  uuid: ^3.0.6
  geocoding: ^2.0.4
  url_launcher: ^6.1.2
  flutter_launcher_icons: ^0.11.0
  flutter_credit_card: ^3.0.7
  change_app_package_name: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter_icons:
  android: "app_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/lottie/
